"use client";

import React from "react";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowUpRight,
  Building2,
  FlaskConical,
  HandHeart,
  HeartHandshake,
  ShieldCheck,
  Sprout,
  Truck,
  Users,
} from "lucide-react";

import { SiteNav } from "@/components/landing/site-nav";
import CTAFooter from "@/components/landing/cta-footer";

const EASE = [0.21, 0.47, 0.32, 0.98] as const;

function Reveal({
  children,
  delay = 0,
  className,
}: {
  children: React.ReactNode;
  delay?: number;
  className?: string;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 28 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-60px" }}
      transition={{ duration: 0.8, delay, ease: EASE }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

/** The eight stakeholders the platform coordinates (proposal §3). */
const STAKEHOLDERS = [
  {
    icon: Users,
    name: "Citizens",
    role: "Register open spaces, request plantation plans, adopt saplings or commit to stewardship, and track their site's growth.",
    tint: "bg-pale",
    ink: "text-emerald",
  },
  {
    icon: Sprout,
    name: "Dhaatri",
    role: "Owner and custodian. Prepares site-specific plantation plans, approves requests, manages funds and public reporting.",
    tint: "bg-mist",
    ink: "text-forest",
  },
  {
    icon: Truck,
    name: "Suppliers",
    role: "Verified network supplying saplings and materials, maintaining inventory visibility and fulfilling orders with tracking.",
    tint: "bg-[#FAEDCD]",
    ink: "text-[#B7791F]",
  },
  {
    icon: HandHeart,
    name: "Volunteers",
    role: "Field supervisors, site inspectors and data collectors — verifying stewardship through geo-tagged visits.",
    tint: "bg-[#E9EDC9]",
    ink: "text-[#7A9E3F]",
  },
  {
    icon: FlaskConical,
    name: "Scientists",
    role: "Define species guidance and the CO₂ methodology, monitor plantations end to end and advise corrective action.",
    tint: "bg-[#D9EAF3]",
    ink: "text-[#3B7EA1]",
  },
  {
    icon: HeartHandshake,
    name: "Donors",
    role: "Contribute funds, receive receipts, and get full visibility of how every rupee flows and is utilised.",
    tint: "bg-[#FBDDD2]",
    ink: "text-[#B4553F]",
  },
  {
    icon: Building2,
    name: "Organisations",
    role: "Purchase carbon credits generated by Dhaatri plantations and monitor the specific sites backing them.",
    tint: "bg-[#E4E0F2]",
    ink: "text-[#6B5CA5]",
  },
  {
    icon: ShieldCheck,
    name: "Platform admin",
    role: "User and role management, master data, supplier onboarding and verification, content and grievance handling.",
    tint: "bg-shell",
    ink: "text-slate",
  },
];

/** Pilot delivery phases (proposal §10). */
const PHASES = [
  {
    weeks: "Weeks 1–2",
    title: "Discovery & design",
    body: "Requirements, workflow finalisation, UX, architecture, and the carbon-engine specification agreed with the scientific panel.",
  },
  {
    weeks: "Weeks 2–5",
    title: "Build — core",
    body: "Registration, the site and request workflow, plantation planning, approvals, RBAC and supplier basics.",
  },
  {
    weeks: "Weeks 4–7",
    title: "Build — field & funds",
    body: "Payments and donations, carbon credits and certificates, stewardship verification, offline-capable geo-tagged monitoring, fund transparency and dashboards.",
  },
  {
    weeks: "Weeks 7–8",
    title: "UAT & pilot launch",
    body: "End-to-end testing, seed data, supplier and volunteer onboarding, store submissions, go-live and hypercare.",
  },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-cream">
      <SiteNav />

      {/* ============================================================ hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0">
          <Image
            src="/scenes/empty-plot.png"
            alt=""
            fill
            className="object-cover"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-b from-ink/88 via-ink/75 to-cream" />
        </div>

        <div className="relative mx-auto max-w-7xl px-4 pb-24 pt-16 sm:px-6 lg:px-8 lg:pb-28 lg:pt-20">
          <Reveal>
            <div className="flex w-fit items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-1.5">
              <Sprout className="size-4 text-mint" />
              <span className="text-[15px] font-medium text-white/85">
                A national public platform
              </span>
            </div>

            <h1 className="mt-6 max-w-[840px] font-onest text-[38px] font-semibold leading-[1.05] tracking-[-2px] text-white sm:text-[52px] lg:text-[62px]">
              Every open space is an{" "}
              <span className="font-playfair italic font-semibold text-mint">
                opportunity
              </span>
            </h1>

            <p className="mt-5 max-w-[620px] text-lg leading-[30px] tracking-[-0.3px] text-white/60">
              Dhaatri exists so that any available land in the country can become planned,
              monitored and measurable green cover — driven by citizens, guided by science,
              and governed with full public transparency.
            </p>
          </Reveal>
        </div>
      </section>

      {/* ========================================================= mission */}
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24">
        <div className="grid gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,0.85fr)] lg:gap-16">
          <Reveal>
            <p className="text-sm font-semibold uppercase tracking-[1.5px] text-emerald">
              Why it exists
            </p>
            <h2 className="mt-3 font-onest text-[30px] font-semibold leading-[1.08] tracking-[-1.6px] text-ink lg:text-[42px]">
              Planting is easy.
              <br />
              Proving it worked is not.
            </h2>

            <div className="mt-6 space-y-4 text-[17px] leading-[29px] text-ink/65">
              <p>
                Plenty of trees get planted. Far fewer are counted a year later. The gap
                between a planting drive and verified green cover is where most impact
                quietly disappears.
              </p>
              <p>
                Dhaatri closes that gap by treating the whole lifecycle as one system —
                assessment, a science-backed plan, verified supply, geo-tagged monitoring,
                and a public ledger of every rupee. Nothing advances on trust alone.
              </p>
            </div>

            <div className="mt-8 flex flex-wrap gap-2.5">
              {["Citizen-driven", "Science-guided", "Publicly auditable"].map((chip) => (
                <span
                  key={chip}
                  className="rounded-full border border-ink/10 bg-white px-4 py-2 text-[14px] font-medium text-ink/70"
                >
                  {chip}
                </span>
              ))}
            </div>
          </Reveal>

          <Reveal delay={0.1}>
            <div className="relative aspect-[4/3] w-full max-w-[460px] overflow-hidden rounded-[28px] bg-pale lg:ml-auto">
              <Image
                src="/features/process.png"
                alt="A plot progressing from bare earth to mature trees"
                fill
                sizes="(max-width: 1024px) 90vw, 460px"
                className="object-contain p-4"
              />
            </div>
          </Reveal>
        </div>
      </section>

      {/* ==================================================== stakeholders */}
      <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8 lg:pb-24">
        <Reveal>
          <p className="text-sm font-semibold uppercase tracking-[1.5px] text-emerald">
            Who makes it work
          </p>
          <h2 className="mt-3 font-onest text-[30px] font-semibold leading-[1.1] tracking-[-1.5px] text-ink lg:text-[40px]">
            Eight roles, one chain
          </h2>
          <p className="mt-4 max-w-[620px] text-[17px] leading-[29px] text-ink/60">
            Each stakeholder owns a distinct step, with a verifiable output the next one
            depends on.
          </p>
        </Reveal>

        <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {STAKEHOLDERS.map((s, i) => (
            <Reveal key={s.name} delay={0.05 * i}>
              <div className="group h-full rounded-[20px] border border-ink/8 bg-white p-6 transition-all hover:-translate-y-1 hover:shadow-[0_18px_40px_-24px_rgba(4,39,24,0.35)]">
                <span
                  className={`flex size-11 items-center justify-center rounded-xl ${s.tint}`}
                >
                  <s.icon className={`size-[19px] ${s.ink}`} />
                </span>
                <h3 className="mt-5 font-onest text-[18px] font-semibold tracking-[-0.4px] text-ink">
                  {s.name}
                </h3>
                <p className="mt-2 text-[14px] leading-[24px] text-ink/55">{s.role}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* ================================================== methodology */}
      <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8 lg:pb-24">
        <Reveal>
          <div className="relative grid gap-10 overflow-hidden rounded-[32px] bg-ink p-8 lg:grid-cols-[minmax(0,1.15fr)_minmax(0,1fr)] lg:gap-14 lg:p-14">
            <div className="pointer-events-none absolute -right-24 -top-28 size-[420px] rounded-full bg-fresh/10 blur-3xl" />

            <div className="relative">
              <p className="text-sm font-semibold uppercase tracking-[1.5px] text-mint">
                The number that has to hold up
              </p>
              <h2 className="mt-4 font-onest text-[30px] font-semibold leading-[1.05] tracking-[-1.6px] text-white lg:text-[42px]">
                A carbon figure you can challenge
              </h2>
              <p className="mt-5 max-w-[460px] text-[17px] leading-[29px] text-white/60">
                CO₂ published by Dhaatri is a function of species, growth stage and{" "}
                <span className="text-mint">verified survival</span> — never a notional
                estimate. The scientific panel owns the formula; the platform implements it
                as a versioned engine.
              </p>

              <ul className="mt-8 space-y-4">
                {[
                  "Every figure traceable to its methodology version",
                  "Traceable to the site and its monitoring data",
                  "The same engine backs every carbon credit sold",
                ].map((line) => (
                  <li key={line} className="flex items-start gap-3">
                    <ShieldCheck className="mt-0.5 size-[18px] shrink-0 text-mint" />
                    <span className="text-[15px] leading-6 text-white/75">{line}</span>
                  </li>
                ))}
              </ul>

              <Link
                href="/impact"
                className="group mt-9 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-[15px] font-medium text-ink transition-colors hover:bg-mint"
              >
                See the published data
                <ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
              </Link>
            </div>

            <div className="relative flex items-center justify-center">
              <div className="absolute size-64 rounded-full bg-mint/10 blur-2xl" />
              <Image
                src="/mascot/sprout-thinking.png"
                alt=""
                width={280}
                height={280}
                className="relative drop-shadow-[0_20px_50px_rgba(0,0,0,0.35)]"
              />
            </div>
          </div>
        </Reveal>
      </section>

      {/* ======================================================== timeline */}
      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8 lg:pb-28">
        <Reveal>
          <p className="text-sm font-semibold uppercase tracking-[1.5px] text-emerald">
            The pilot
          </p>
          <h2 className="mt-3 font-onest text-[30px] font-semibold leading-[1.1] tracking-[-1.5px] text-ink lg:text-[40px]">
            Eight weeks to go-live
          </h2>
          <p className="mt-4 max-w-[620px] text-[17px] leading-[29px] text-ink/60">
            Scoped to a single locality, exercising every core flow before national rollout.
          </p>
        </Reveal>

        <div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">
          {PHASES.map((p, i) => (
            <Reveal key={p.title} delay={0.08 * i}>
              <div className="relative">
                {/* connecting rule — the phases overlap rather than queue */}
                <div className="flex items-center gap-3">
                  <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-ink font-onest text-[14px] font-semibold text-white">
                    {i + 1}
                  </span>
                  <span className="h-px flex-1 bg-ink/12" />
                </div>

                <p className="mt-5 text-[13px] font-semibold uppercase tracking-[1.2px] text-emerald">
                  {p.weeks}
                </p>
                <h3 className="mt-2 font-onest text-[20px] font-semibold leading-tight tracking-[-0.6px] text-ink">
                  {p.title}
                </h3>
                <p className="mt-3 text-[14px] leading-[24px] text-ink/55">{p.body}</p>
              </div>
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.3}>
          <div className="mt-14 flex flex-col gap-4 rounded-[20px] bg-ink/[0.04] px-6 py-5 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-[14px] leading-6 text-ink/60">
              Built by{" "}
              <span className="font-medium text-ink">Canarys Automations Pvt. Ltd.</span> —
              the pilot runs on the same architecture intended for national scale, so new
              regions, languages and supplier networks are configuration, not rebuilds.
            </p>
            <Link
              href="/register"
              className="group flex shrink-0 items-center gap-2 text-[15px] font-medium text-emerald"
            >
              Register your space
              <ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
            </Link>
          </div>
        </Reveal>
      </section>

      <CTAFooter />
    </div>
  );
}
