"use client";

import React, { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowUpRight, CreditCard, HeartHandshake, Building2, Check } from "lucide-react";

/** Engagement and funding models (proposal §4). */
const MODELS = [
  {
    tag: "Model A",
    icon: CreditCard,
    title: "Paid adoption",
    price: "You fund the saplings",
    body: "Pay for the saplings and the plan. Dhaatri coordinates supply, planting and monitoring end to end.",
    points: [
      "Science-backed plantation plan",
      "Verified supplier fulfilment",
      "Geo-tagged planting and monitoring",
      "Your contribution shown in the public ledger",
    ],
    dark: false,
  },
  {
    tag: "Model B",
    icon: HeartHandshake,
    title: "Stewardship",
    price: "You commit your care",
    body: "Pay nothing. Formally commit to nurturing the plants grown on your space, verified through check-ins.",
    points: [
      "No payment required",
      "Geo-tagged photo check-ins by you",
      "Periodic volunteer inspections",
      "Compliance feeds survival tracking",
    ],
    dark: true,
    featured: true,
  },
  {
    tag: "For organisations",
    icon: Building2,
    title: "Carbon credits",
    price: "1 unit = 1 tonne CO₂e",
    body: "Purchase methodology-backed offset units generated by verified Dhaatri plantations.",
    points: [
      "Digital certificates on purchase",
      "Live monitoring of backing sites",
      "Credit retirement tracking",
      "Proceeds join the same public ledger",
    ],
    dark: false,
  },
];

export default function EngagementModels() {
  const [hovered, setHovered] = useState<number | null>(null);

  return (
    <section className="relative w-full bg-cream py-20 lg:py-28">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, ease: [0.21, 0.47, 0.32, 0.98] }}
          className="max-w-[720px]"
        >
          <p className="text-sm font-semibold tracking-[1.5px] uppercase text-emerald mb-4">
            How you take part
          </p>
          <h2 className="font-onest text-[34px] sm:text-[44px] lg:text-[52px] font-semibold leading-[1.1] tracking-[-2px] text-ink">
            Contribute money, or{" "}
            <span className="font-playfair italic font-semibold text-black opacity-45">
              care
            </span>
          </h2>
          <p className="mt-5 text-lg leading-[30px] tracking-[-0.3px] text-ink/70">
            Not everyone can fund a plantation, and not everyone has land. Both are
            genuine contributions — the platform treats them as equals.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 mt-14 items-stretch">
          {MODELS.map((m, i) => {
            const Icon = m.icon;
            const lift = hovered === i;
            return (
              <motion.div
                key={m.title}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{
                  duration: 0.8,
                  delay: i * 0.12,
                  ease: [0.21, 0.47, 0.32, 0.98],
                }}
                onMouseEnter={() => setHovered(i)}
                onMouseLeave={() => setHovered(null)}
                className={
                  "relative flex flex-col rounded-[28px] p-8 lg:p-9 border transition-all duration-300 " +
                  (m.dark
                    ? "bg-ink border-ink text-white"
                    : "bg-white border-ink/5 text-ink") +
                  (lift ? " -translate-y-1.5 shadow-[0_24px_50px_-28px_rgba(4,39,24,0.45)]" : "")
                }
              >
                {m.featured && (
                  <span className="absolute top-7 right-7 rounded-full bg-mint px-3 py-1 text-[12px] font-semibold text-ink">
                    Most chosen
                  </span>
                )}

                <div
                  className={
                    "w-12 h-12 rounded-2xl flex items-center justify-center " +
                    (m.dark ? "bg-white/10" : "bg-pale")
                  }
                >
                  <Icon className={"w-[22px] h-[22px] " + (m.dark ? "text-mint" : "text-emerald")} />
                </div>

                <p
                  className={
                    "mt-6 text-sm font-semibold uppercase tracking-[1.5px] " +
                    (m.dark ? "text-mint" : "text-emerald")
                  }
                >
                  {m.tag}
                </p>

                <h3 className="mt-2 font-onest text-[28px] font-semibold leading-tight tracking-[-1px]">
                  {m.title}
                </h3>

                <p
                  className={
                    "mt-1 font-onest text-[17px] font-medium " +
                    (m.dark ? "text-white/70" : "text-ink/55")
                  }
                >
                  {m.price}
                </p>

                <p
                  className={
                    "mt-4 text-[15px] leading-[26px] " +
                    (m.dark ? "text-white/60" : "text-ink/60")
                  }
                >
                  {m.body}
                </p>

                <ul className="mt-6 flex flex-col gap-3">
                  {m.points.map((p) => (
                    <li key={p} className="flex items-start gap-2.5">
                      <span
                        className={
                          "mt-0.5 flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-full " +
                          (m.dark ? "bg-mint/20" : "bg-pale")
                        }
                      >
                        <Check className={"h-3 w-3 " + (m.dark ? "text-mint" : "text-emerald")} />
                      </span>
                      <span
                        className={
                          "text-[14px] leading-[22px] " +
                          (m.dark ? "text-white/70" : "text-ink/65")
                        }
                      >
                        {p}
                      </span>
                    </li>
                  ))}
                </ul>

                <Link
                  href="/register"
                  className={
                    "mt-8 group flex items-center justify-between rounded-full px-5 h-12 transition-colors " +
                    (m.dark
                      ? "bg-white text-ink hover:bg-mint"
                      : "bg-ink text-white hover:bg-emerald")
                  }
                >
                  <span className="text-[15px] font-medium">Get started</span>
                  <ArrowUpRight className="h-4 w-4 transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
                </Link>
              </motion.div>
            );
          })}
        </div>

        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.4 }}
          className="mt-8 text-center text-[14px] leading-6 text-ink/45 max-w-[720px] mx-auto"
        >
          Pilot credits are platform-issued and methodology-backed. Certification under
          external standards (Verra, Gold Standard, India CCTS) is the Phase 2 path to
          market-tradable credits.
        </motion.p>
      </div>
    </section>
  );
}
